version: 0.2

phases:
  install:
    run-as: NODE JS APP
    on-failure: ABORT
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Testing the Node.js/Express application...
      - npm run test
  post_build:
    commands:
      - echo Test completed.
artifacts:
  files:
    - '**/*'
  discard-paths: yes
